"use client";

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/components/ui/use-toast';
import { downloadTextFile } from '@/lib/browser-download';
import { 
  Download, 
  Upload, 
  Plug, 
  Building, 
  Lightbulb, 
  Calculator,
  Code,
  ExternalLink,
  Copy,
  Zap
} from 'lucide-react';
import { LightingSchedule } from '../utils/lightingStandards';
import { format } from 'date-fns';

interface ProfessionalIntegrationsProps {
  currentSchedule: LightingSchedule | null;
}

const ProfessionalIntegrations: React.FC<ProfessionalIntegrationsProps> = ({
  currentSchedule
}) => {
  const [revitApiUrl, setRevitApiUrl] = useState('');
  const [dialuxApiUrl, setDialuxApiUrl] = useState('');
  const [agi32ApiUrl, setAgi32ApiUrl] = useState('');
  const [webhookUrl, setWebhookUrl] = useState('');
  const { toast } = useToast();

  // Generate Revit-compatible lighting families data
  const exportToRevit = () => {
    if (!currentSchedule) {
      toast({
        title: "No Schedule Available",
        description: "Please generate a lighting schedule first.",
        variant: "destructive"
      });
      return;
    }

    // Create Revit family parameters format
    const revitData = {
      FamilyName: "CircadianLightingFixture",
      Category: "Lighting Fixtures",
      Parameters: {
        "Circadian_Schedule_Name": currentSchedule.name,
        "Schedule_Description": currentSchedule.description,
        "Peak_Intensity": Math.max(...currentSchedule.schedule.map(p => p.intensity)),
        "Color_Temperature_Range": `${Math.min(...currentSchedule.schedule.map(p => p.temperature))}-${Math.max(...currentSchedule.schedule.map(p => p.temperature))}K`,
        "Schedule_Points": currentSchedule.schedule.length,
        "Melanopic_Ratio_Peak": 0.85, // Calculate based on schedule
        "CRI_Minimum": 90,
        "Energy_Efficiency": "Class A+"
      },
      ScheduleData: currentSchedule.schedule.map(point => ({
        Hour: point.time,
        Intensity_Percent: point.intensity,
        Color_Temperature_K: point.temperature,
        Power_Consumption_W: Math.round(point.intensity * 0.8), // Estimate based on intensity
        Melanopic_Lux: Math.round(point.intensity * point.temperature / 100)
      })),
      SharedParameters: {
        "CIRCADIAN_ENABLED": true,
        "SCHEDULE_TYPE": currentSchedule.name,
        "WELL_CERTIFIED": true,
        "LEED_POINTS": 2
      }
    };

    downloadTextFile(
      JSON.stringify(revitData, null, 2),
      `revit-lighting-family-${format(new Date(), 'yyyy-MM-dd')}.json`,
      'application/json',
    );

    toast({
      title: "Revit Export Complete",
      description: "Lighting family data exported for Revit integration."
    });
  };

  // Generate DIALux-compatible .ldt file
  const exportToDIALux = () => {
    if (!currentSchedule) {
      toast({
        title: "No Schedule Available",
        description: "Please generate a lighting schedule first.",
        variant: "destructive"
      });
      return;
    }

    // Create LDT (Luminaire Data) format for DIALux
    const ldtContent = `# DIALux Luminaire Data File
# Generated by Circadian Lighting Designer
# ${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}

[LUMINAIRE]
Name=${currentSchedule.name.replace(/\s+/g, '_')}
Manufacturer=Circadian_Systems
Type=LED_Circadian
Description=${currentSchedule.description}

[LAMP]
LampType=LED
Power=${Math.max(...currentSchedule.schedule.map(p => p.intensity))}W
ColorTemperatureMin=${Math.min(...currentSchedule.schedule.map(p => p.temperature))}K
ColorTemperatureMax=${Math.max(...currentSchedule.schedule.map(p => p.temperature))}K
CRI=95
Lifetime=50000h

[CONTROL]
Type=Circadian
DimmingRange=0-100%
ColorTuning=Yes
Protocol=DALI

[SCHEDULE_DATA]
Points=${currentSchedule.schedule.length}
${currentSchedule.schedule.map(point => 
  `${point.time.toFixed(2)}\t${point.intensity}\t${point.temperature}\t${(point.intensity * 100).toFixed(0)}`
).join('\n')}

[PHOTOMETRIC]
LuminousFlux=${Math.max(...currentSchedule.schedule.map(p => p.intensity * 100))}lm
BeamAngle=120
FieldAngle=140
ULOR=0.1
DLOR=0.9

[CERTIFICATIONS]
WELL_Building_Standard=Yes
LEED_Compliant=Yes
Energy_Star=Yes
DLC_Listed=Yes
`;

    downloadTextFile(ldtContent, `dialux-luminaire-${format(new Date(), 'yyyy-MM-dd')}.ldt`, 'text/plain');

    toast({
      title: "DIALux Export Complete",
      description: "Luminaire data file (.ldt) exported for DIALux."
    });
  };

  // Generate AGi32-compatible .ag3 data
  const exportToAGi32 = () => {
    if (!currentSchedule) {
      toast({
        title: "No Schedule Available",
        description: "Please generate a lighting schedule first.",
        variant: "destructive"
      });
      return;
    }

    // Create AGi32 project data
    const agi32Data = {
      ProjectInfo: {
        Name: currentSchedule.name,
        Description: currentSchedule.description,
        Created: format(new Date(), 'yyyy-MM-dd HH:mm:ss'),
        Software: "Circadian Lighting Designer",
        Version: "1.0"
      },
      LuminaireData: {
        Manufacturer: "Circadian Systems",
        Model: currentSchedule.name.replace(/\s+/g, '_'),
        Type: "LED Circadian Fixture",
        Wattage: Math.max(...currentSchedule.schedule.map(p => p.intensity)),
        Lumens: Math.max(...currentSchedule.schedule.map(p => p.intensity * 100)),
        Efficacy: 100, // lumens per watt
        ColorTemperature: `Tunable ${Math.min(...currentSchedule.schedule.map(p => p.temperature))}-${Math.max(...currentSchedule.schedule.map(p => p.temperature))}K`,
        CRI: 95,
        DimmingControl: "0-100%",
        CircadianControl: true
      },
      ScheduleData: {
        Type: "Circadian",
        Points: currentSchedule.schedule.map(point => ({
          Time: point.time,
          DimmingLevel: point.intensity / 100,
          ColorTemperature: point.temperature,
          LuminousFlux: point.intensity * 100,
          PowerConsumption: point.intensity * 0.8,
          MelanopicRatio: point.temperature > 5000 ? 0.8 : 0.3
        }))
      },
      CalculationParameters: {
        SurfaceReflectances: {
          Ceiling: 0.8,
          Walls: 0.5,
          Floor: 0.2
        },
        MaintenanceFactor: 0.8,
        UtilityFactor: 0.9
      }
    };

    downloadTextFile(
      JSON.stringify(agi32Data, null, 2),
      `agi32-project-${format(new Date(), 'yyyy-MM-dd')}.json`,
      'application/json',
    );

    toast({
      title: "AGi32 Export Complete",
      description: "Project data exported for AGi32 integration."
    });
  };

  // Generate plugin installation script
  const generatePluginScript = () => {
    const apiEndpoint = `${window.location.origin}/api/lighting-schedule`;
    
    const pluginScript = `// Circadian Lighting Designer Plugin
// Installation script for professional software integration

const CircadianLightingAPI = {
  baseUrl: "${apiEndpoint}",
  
  // Get current lighting schedule
  async getCurrentSchedule() {
    try {
      const response = await fetch(this.baseUrl + '/current');
      return await response.json();
    } catch (error) {
      console.error('Failed to fetch schedule:', error);
      return null;
    }
  },
  
  // Send lighting parameters to external software
  async sendToRevit(projectData) {
    return await this.sendToSoftware('revit', projectData);
  },
  
  async sendToDIALux(projectData) {
    return await this.sendToSoftware('dialux', projectData);
  },
  
  async sendToAGi32(projectData) {
    return await this.sendToSoftware('agi32', projectData);
  },
  
  async sendToSoftware(software, data) {
    try {
      const response = await fetch(this.baseUrl + '/integrate/' + software, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
      });
      return await response.json();
    } catch (error) {
      console.error('Integration failed:', error);
      return { success: false, error: error.message };
    }
  }
};

// Usage examples:
// CircadianLightingAPI.getCurrentSchedule().then(schedule => console.log(schedule));
// CircadianLightingAPI.sendToRevit({ projectId: 'your-project-id', familyType: 'LED_Fixture' });
`;

    downloadTextFile(pluginScript, 'circadian-lighting-plugin.js', 'text/javascript');

    toast({
      title: "Plugin Script Generated",
      description: "JavaScript integration script downloaded."
    });
  };

  // Copy API endpoints to clipboard
  const copyAPIEndpoints = () => {
    const endpoints = `Circadian Lighting Designer API Endpoints:

Base URL: ${window.location.origin}/api

GET /lighting-schedule/current
- Returns current active lighting schedule

POST /lighting-schedule/integrate/revit
- Send schedule data to Revit
- Body: { projectId, familyData, scheduleData }

POST /lighting-schedule/integrate/dialux  
- Send schedule data to DIALux
- Body: { projectId, luminaireData, scheduleData }

POST /lighting-schedule/integrate/agi32
- Send schedule data to AGi32
- Body: { projectId, calculationData, scheduleData }

POST /webhook/lighting-update
- Webhook for real-time updates
- Body: { scheduleId, changes, timestamp }

Authentication: Bearer token or API key required
Content-Type: application/json`;

    navigator.clipboard.writeText(endpoints).then(() => {
      toast({
        title: "API Endpoints Copied",
        description: "API documentation copied to clipboard."
      });
    });
  };

  // Send test webhook
  const sendTestWebhook = async () => {
    if (!webhookUrl) {
      toast({
        title: "Webhook URL Required",
        description: "Please enter a webhook URL first.",
        variant: "destructive"
      });
      return;
    }

    if (!currentSchedule) {
      toast({
        title: "No Schedule Available",
        description: "Please generate a lighting schedule first.",
        variant: "destructive"
      });
      return;
    }

    try {
      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        mode: 'no-cors',
        body: JSON.stringify({
          event: 'schedule_update',
          schedule: currentSchedule,
          timestamp: new Date().toISOString(),
          source: 'circadian-lighting-designer'
        })
      });

      toast({
        title: "Webhook Test Sent",
        description: "Test data sent to your webhook endpoint."
      });
    } catch (error) {
      toast({
        title: "Webhook Failed",
        description: "Could not send test webhook. Check the URL and try again.",
        variant: "destructive"
      });
    }
  };

  return (
    <div className="space-y-6">
      {/* Professional Software Exports */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Building className="h-5 w-5 mr-2" />
            Professional Software Integration
          </CardTitle>
          <CardDescription>
            Export lighting schedules for use in industry-standard design software
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Revit Integration */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="font-semibold flex items-center">
                  <Building className="h-4 w-4 mr-2" />
                  Autodesk Revit
                </h3>
                <p className="text-sm text-gray-600">
                  Export lighting families with circadian parameters for BIM integration
                </p>
              </div>
              <Button onClick={exportToRevit} disabled={!currentSchedule}>
                <Download className="h-4 w-4 mr-2" />
                Export Family
              </Button>
            </div>
            <div className="flex gap-2">
              <Badge variant="outline">Lighting Families</Badge>
              <Badge variant="outline">Shared Parameters</Badge>
              <Badge variant="outline">WELL Certified</Badge>
            </div>
          </div>

          <Separator />

          {/* DIALux Integration */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="font-semibold flex items-center">
                  <Lightbulb className="h-4 w-4 mr-2" />
                  DIALux / DIALux evo
                </h3>
                <p className="text-sm text-gray-600">
                  Generate luminaire data files (.ldt) for lighting calculations
                </p>
              </div>
              <Button onClick={exportToDIALux} disabled={!currentSchedule}>
                <Download className="h-4 w-4 mr-2" />
                Export LDT
              </Button>
            </div>
            <div className="flex gap-2">
              <Badge variant="outline">Photometric Data</Badge>
              <Badge variant="outline">Color Tuning</Badge>
              <Badge variant="outline">DALI Control</Badge>
            </div>
          </div>

          <Separator />

          {/* AGi32 Integration */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <h3 className="font-semibold flex items-center">
                  <Calculator className="h-4 w-4 mr-2" />
                  AGi32
                </h3>
                <p className="text-sm text-gray-600">
                  Project data for lighting calculations and energy analysis
                </p>
              </div>
              <Button onClick={exportToAGi32} disabled={!currentSchedule}>
                <Download className="h-4 w-4 mr-2" />
                Export Project
              </Button>
            </div>
            <div className="flex gap-2">
              <Badge variant="outline">Energy Analysis</Badge>
              <Badge variant="outline">Illuminance Calc</Badge>
              <Badge variant="outline">Daylight Integration</Badge>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Plugin & API Integration */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Plug className="h-5 w-5 mr-2" />
            Plugin & API Integration
          </CardTitle>
          <CardDescription>
            Integrate directly with your existing software workflow
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Button onClick={generatePluginScript} variant="outline" className="h-20 flex-col">
              <Code className="h-6 w-6 mb-2" />
              <span>Download Plugin Script</span>
              <span className="text-xs text-gray-500">JavaScript integration code</span>
            </Button>
            
            <Button onClick={copyAPIEndpoints} variant="outline" className="h-20 flex-col">
              <Copy className="h-6 w-6 mb-2" />
              <span>Copy API Endpoints</span>
              <span className="text-xs text-gray-500">REST API documentation</span>
            </Button>
          </div>

          <Separator />

          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="webhook-url">Webhook URL (for real-time updates)</Label>
              <div className="flex gap-2">
                <Input
                  id="webhook-url"
                  placeholder="https://your-software.com/api/webhook"
                  value={webhookUrl}
                  onChange={(e) => setWebhookUrl(e.target.value)}
                />
                <Button onClick={sendTestWebhook} disabled={!webhookUrl}>
                  <Zap className="h-4 w-4 mr-2" />
                  Test
                </Button>
              </div>
              <p className="text-xs text-gray-500">
                Send real-time lighting schedule updates to your software
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Integration Examples */}
      <Card>
        <CardHeader>
          <CardTitle>Integration Examples</CardTitle>
          <CardDescription>
            Common workflow integrations with professional software
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
              <h4 className="font-semibold text-blue-900">Revit → Circadian Lighting</h4>
              <p className="text-sm text-blue-800 mt-1">
                1. Export room geometry from Revit<br/>
                2. Generate circadian schedule based on space usage<br/>
                3. Import lighting families with circadian parameters<br/>
                4. Update MEP systems with control requirements
              </p>
            </div>
            
            <div className="p-4 bg-green-50 rounded-lg border border-green-200">
              <h4 className="font-semibold text-green-900">DIALux → Performance Analysis</h4>
              <p className="text-sm text-green-800 mt-1">
                1. Import luminaire data (.ldt) into DIALux<br/>
                2. Calculate illuminance and circadian metrics<br/>
                3. Verify WELL Building Standard compliance<br/>
                4. Generate photometric reports
              </p>
            </div>
            
            <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
              <h4 className="font-semibold text-purple-900">AGi32 → Energy Modeling</h4>
              <p className="text-sm text-purple-800 mt-1">
                1. Import project data with circadian schedules<br/>
                2. Calculate annual energy consumption<br/>
                3. Optimize for LEED daylight credits<br/>
                4. Generate compliance documentation
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default ProfessionalIntegrations;