CREATE TABLE "worked_example_templates" (
	"key" text PRIMARY KEY NOT NULL,
	"version" text NOT NULL,
	"sort_order" integer NOT NULL,
	"definition" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "worked_example_templates_sort_order_idx" ON "worked_example_templates" USING btree ("sort_order");
--> statement-breakpoint
-- Shared template rows are copied into fresh user-owned records; no application mutation path targets this table.
-- Harbor Heights uses a fixed 2026-07-10 Amsterdam sun-time snapshot and intentionally contains no ROI inputs.
INSERT INTO "worked_example_templates" ("key", "version", "sort_order", "definition") VALUES
	('northbridge-academy', '2026-07-10-v1', 1, '{"project":{"name":"Example — Northbridge Academy classrooms","description":"Illustrative demo case; figures and schedules are not site measurements or savings claims.","client":"","location":"New York, NY","projectType":"education","tags":["classrooms","retrofit","WELL"]},"scenario":{"name":"Teaching-day schedule","description":"Optimized for classroom environments to enhance student alertness, learning capacity and wellbeing.","source":"standard_preset","presetName":"Educational Setting","schedule":{"name":"Educational Setting","description":"Optimized for classroom environments to enhance student alertness, learning capacity and wellbeing.","schedule":[{"time":0,"intensity":5,"temperature":2200},{"time":7,"intensity":50,"temperature":3500},{"time":8,"intensity":90,"temperature":5000},{"time":9,"intensity":100,"temperature":6000},{"time":12,"intensity":100,"temperature":6500},{"time":15,"intensity":90,"temperature":5500},{"time":17,"intensity":70,"temperature":4000},{"time":20,"intensity":40,"temperature":3000},{"time":22,"intensity":10,"temperature":2500},{"time":24,"intensity":5,"temperature":2200}],"citations":["Mott, M.S. et al. (2012). Illuminating the effects of dynamic lighting on student learning. SAGE Open, 2(2).","Sleegers, P.J. et al. (2016). Light effects on mental activity: classroom studies using dynamic lighting systems. LEUKOS, 12(1-2), 27-44."]},"scheduleInputs":{"presetName":"Educational Setting"}},"reportName":"School classroom case report","roiInputs":{"employees":95,"averageSalary":57000,"implementationCost":145000,"annualLightingEnergyCost":45000,"currentAbsenteeism":7.5,"currentTurnover":10}}'::jsonb),
	('meridian-tower', '2026-07-10-v1', 2, '{"project":{"name":"Example — Meridian Tower Class A offices","description":"Illustrative demo case; figures and schedules are not site measurements or savings claims.","client":"","location":"New York, NY","projectType":"office","tags":["Class A","workplace","retrofit"]},"scenario":{"name":"Core-office day schedule","description":"Designed for office environments to promote alertness during the day and proper wind-down in the evening.","source":"standard_preset","presetName":"Optimal Office Lighting","schedule":{"name":"Optimal Office Lighting","description":"Designed for office environments to promote alertness during the day and proper wind-down in the evening.","schedule":[{"time":0,"intensity":5,"temperature":2200},{"time":5,"intensity":5,"temperature":2200},{"time":6,"intensity":30,"temperature":3000},{"time":7,"intensity":60,"temperature":4000},{"time":8,"intensity":80,"temperature":5000},{"time":9,"intensity":100,"temperature":6000},{"time":12,"intensity":100,"temperature":6500},{"time":16,"intensity":80,"temperature":5000},{"time":18,"intensity":60,"temperature":3500},{"time":20,"intensity":40,"temperature":2700},{"time":22,"intensity":10,"temperature":2200},{"time":24,"intensity":5,"temperature":2200}],"citations":["Figueiro, M.G. et al. (2017). Circadian-effective light and its impact on alertness in office workers. Lighting Research & Technology, 49(2), 196-214.","WELL Building Standard v2 Concept: Light, Feature L03: Circadian lighting design."]},"scheduleInputs":{"presetName":"Optimal Office Lighting"}},"reportName":"Class A office case report","roiInputs":{"employees":420,"averageSalary":95000,"implementationCost":350000,"annualLightingEnergyCost":110000,"currentAbsenteeism":7,"currentTurnover":15}}'::jsonb),
	('st-anselm-outpatient', '2026-07-10-v1', 3, '{"project":{"name":"Example — St. Anselm outpatient facility","description":"Illustrative demo case; figures and schedules are not site measurements or savings claims.","client":"","location":"New York, NY","projectType":"healthcare","tags":["outpatient","staff","patient experience"]},"scenario":{"name":"Day-shift clinical schedule","description":"Schedule for healthcare settings that supports staff alertness and patient recovery cycles.","source":"standard_preset","presetName":"Healthcare Environment","schedule":{"name":"Healthcare Environment","description":"Schedule for healthcare settings that supports staff alertness and patient recovery cycles.","schedule":[{"time":0,"intensity":10,"temperature":2200},{"time":5,"intensity":10,"temperature":2200},{"time":6,"intensity":40,"temperature":3500},{"time":7,"intensity":70,"temperature":4500},{"time":8,"intensity":90,"temperature":5500},{"time":9,"intensity":100,"temperature":6000},{"time":12,"intensity":100,"temperature":6500},{"time":16,"intensity":90,"temperature":5500},{"time":18,"intensity":70,"temperature":4500},{"time":20,"intensity":50,"temperature":3500},{"time":22,"intensity":20,"temperature":2700},{"time":24,"intensity":10,"temperature":2200}],"citations":["Giménez, M.C. et al. (2017). Patient room lighting influences on sleep, appraisal and mood in hospitalized people. Journal of Sleep Research, 26(2), 236-246.","Bernhofer, E.I. et al. (2014). Hospital lighting and its association with sleep, mood and pain in medical inpatients. Journal of Advanced Nursing, 70(5), 1164-1173."]},"scheduleInputs":{"presetName":"Healthcare Environment"}},"reportName":"Healthcare facility case report","roiInputs":{"employees":230,"averageSalary":74000,"implementationCost":300000,"annualLightingEnergyCost":80000,"currentAbsenteeism":9,"currentTurnover":18}}'::jsonb),
	('harbor-heights', '2026-07-10-v1', 4, '{"project":{"name":"Example — Harbor Heights apartments","description":"Illustrative demo case; figures and schedules are not site measurements or savings claims.","client":"","location":"Amsterdam","projectType":"residential","tags":["multifamily","resident wellbeing","common areas"]},"scenario":{"name":"Resident wind-down schedule","description":"Wake 6.5, sleep 22.5, max 80%","source":"custom","schedule":{"name":"Resident wind-down schedule","description":"Wake 6.5, sleep 22.5, max 80%","schedule":[{"time":0,"intensity":5,"temperature":2200},{"time":5.479,"intensity":85,"temperature":5500},{"time":6.479,"intensity":80,"temperature":6500},{"time":6.5,"intensity":24,"temperature":3000},{"time":7.5,"intensity":48,"temperature":4000},{"time":8.5,"intensity":64,"temperature":5000},{"time":9.5,"intensity":80,"temperature":6000},{"time":12.5,"intensity":80,"temperature":6500},{"time":17,"intensity":64,"temperature":5000},{"time":19,"intensity":48,"temperature":3500},{"time":21,"intensity":32,"temperature":2700},{"time":21.047,"intensity":80,"temperature":4200},{"time":22.047,"intensity":60,"temperature":3500},{"time":23,"intensity":8,"temperature":2200},{"time":23.047,"intensity":30,"temperature":2700},{"time":24,"intensity":5,"temperature":2200}],"citations":["Custom schedule based on peer-reviewed lighting research principles."]},"scheduleInputs":{"wakeTime":6.5,"sleepTime":22.5,"maxIntensity":80,"basePresetName":"Optimal Office Lighting","useSunTimes":true,"location":{"latitude":52.3676,"longitude":4.9041,"timezone":"Europe/Amsterdam"}}},"reportName":"Multi-residential lighting case report"}'::jsonb);
